name = "admin-service"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
AUTH0_DOMAIN = ""
AUTH0_CLIENT_ID = ""
AUTH0_M2M_CLIENT_ID = ""
AUTH0_M2M_CLIENT_SECRET = ""

[[d1_databases]]
binding = "USERS_DB"
database_name = "users-db"
database_id = "9d0bce6c-bd8d-4223-9ceb-c79557ce66b9"

[[d1_databases]]
binding = "PROPERTIES_DB"
database_name = "properties-db"
database_id = ""

[[d1_databases]]
binding = "BOOKINGS_DB"
database_name = "bookings-db"
database_id = ""

[[d1_databases]]
binding = "PAYMENTS_DB"
database_name = "payments-db"
database_id = ""

[env.sit]
name = "admin-service-sit"
[[env.sit.d1_databases]]
binding = "USERS_DB"
database_name = "users-db-sit"
database_id = "9d0bce6c-bd8d-4223-9ceb-c79557ce66b9"
[[env.sit.d1_databases]]
binding = "PROPERTIES_DB"
database_name = "properties-db-sit"
database_id = ""
[[env.sit.d1_databases]]
binding = "BOOKINGS_DB"
database_name = "bookings-db-sit"
database_id = ""
[[env.sit.d1_databases]]
binding = "PAYMENTS_DB"
database_name = "payments-db-sit"
database_id = ""

[env.uat]
name = "admin-service-uat"
[[env.uat.d1_databases]]
binding = "USERS_DB"
database_name = "users-db-uat"
database_id = "c6aa0fc5-a772-4340-b391-72c0cc2f1982"
[[env.uat.d1_databases]]
binding = "PROPERTIES_DB"
database_name = "properties-db-uat"
database_id = ""
[[env.uat.d1_databases]]
binding = "BOOKINGS_DB"
database_name = "bookings-db-uat"
database_id = ""
[[env.uat.d1_databases]]
binding = "PAYMENTS_DB"
database_name = "payments-db-uat"
database_id = ""

[env.prod]
name = "admin-service-prod"
[[env.prod.d1_databases]]
binding = "USERS_DB"
database_name = "users-db-prod"
database_id = "8909eb50-af8f-4bcf-938a-0f0a57708e5d"
[[env.prod.d1_databases]]
binding = "PROPERTIES_DB"
database_name = "properties-db-prod"
database_id = ""
[[env.prod.d1_databases]]
binding = "BOOKINGS_DB"
database_name = "bookings-db-prod"
database_id = ""
[[env.prod.d1_databases]]
binding = "PAYMENTS_DB"
database_name = "payments-db-prod"
database_id = ""
