name = "payments-service"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "PAYMENTS_DB"
database_name = "payments-db"
database_id = "2a92b8c2-23c1-44cc-91b4-dea2c4673a12"

[env.sit]
name = "payments-service-sit"
[[env.sit.d1_databases]]
binding = "PAYMENTS_DB"
database_name = "payments-db-sit"
database_id = "2a92b8c2-23c1-44cc-91b4-dea2c4673a12"

[env.uat]
name = "payments-service-uat"
[[env.uat.d1_databases]]
binding = "PAYMENTS_DB"
database_name = "payments-db-uat"
database_id = "b41e337d-b5ba-4e7e-b79b-e78ad8825389"

[env.prod]
name = "payments-service-prod"
[[env.prod.d1_databases]]
binding = "PAYMENTS_DB"
database_name = "payments-db-prod"
database_id = "ccbe8d00-4063-463b-9e28-0632845f3fe8"
